### ISSUE TITLE
Please Relase under a free licence

### ISSUE THREAD

**Issue by kuldeepdhaka** [ab2tech/KiCad#6]
Please release atleast under CC-BY-SA 4.0 
**CC BY-NC-SA 3.0 is a non-free licence**
also, via CC-BY-SA 4.0, code can be imported under GPLv3 (see [this](https://creativecommons.org/compatiblelicenses/))    (note: *not* GPLv3 or later BUT afaiu (inal) possible via indirect compatiblility with future licence)
also, if licenced under GPLv3 or later, that would be too cool!  (probebly you are ok, if you atleast licence under CC-BY-SA 4.0)

**Comment by austinbeam** [comment]
Hi @kuldeepdhaka,
Apologies for the delayed response -- I was on vacation when this came in, and didn't get back around too it very quickly.

We've released under a 'non-commercial' license simply because we feel like this is more of a contribution to hobbyists and enthusiasts like us rather than money-making entities. That said, we aren't opposed to releasing under a separate license individually given the right circumstances. I would encourage you to contact us directly if there is a specific use-case or need that you may have where our existing license does not accommodate.

Thanks for reaching out and for using/sharing our work -- hope it has helped you in some way.

Have a nice day.
